### PR TITLE
Add installation instructions for Gentoo

### PR DESCRIPTION
**Pull request by azahi**

### CODE REVIEW

**Comment by metakirby5** [comment]
Thanks for the contribution! One suggestion I have is to move zenbu to `app-misc` instead of `x11-misc` since the program is not dependent on x11, but it's understandable if you can't move it.

**Comment by azahi** [comment]
Seems reasonable enough, I'll do that next.

**Comment by azahi** [comment]
OK. I've changed the category and did some tweaks to the build system. For some reason I can't add another commit to this PR and opening another one doesn't seem like a good practice. You might want to change it to ``app-misc`` in the README yourself. :smile:

**Comment by metakirby5** [comment]
Done!

**Pull request merged**
